all: stack_linkedList queueTwostacks treeList

stack_linkedList: stack_linkedList.cpp
	g++ -Wall -o stack_linkedList stack_linkedList.cpp

queueTwostacks: queueTwostacks.cpp
	g++ -Wall -o queueTwostacks queueTwostacks.cpp

treeList: treeList.cpp
	g++ -Wall -o treeList treeList.cpp

clean:
	rm stack_linkedList queueTwostacks treeList