all: problem1 problem2 problem3 problem4 problem5 problem6

problem1: lists.cpp
	g++ -Wall -o problem1 lists.cpp

problem2: 2_2.cpp
	g++ -Wall -o problem2 2_2.cpp

problem3: WindGauge.cpp testWindGauge.cpp WindGauge.h
	g++ -Wall -o problem3 WindGauge.cpp testWindGauge.cpp

problem4: 2_4.cpp
	g++ -Wall -o problem4 2_4.cpp

problem5: 2_5.cpp
	g++ -Wall -o problem5 2_5.cpp

problem6: 2_6.cpp
	g++ -Wall -o problem6 2_6.cpp

clean:
	rm problem1 problem2 problem3 problem4 problem5 problem6