default: problem1 problem2 problem3 problem4 problem5

problem1: 1_1.cpp
	g++ -Wall -o problem1 1_1.cpp

problem2: testStack.cpp Stack.h
	g++ -Wall -o problem2 testStack.cpp

problem3: testLinkedList.cpp LinkedList.h
	g++ -Wall -o problem3 testLinkedList.cpp

problem4: a1_p1.cpp
	g++ -Wall -o problem4 a1_p1.cpp

problem5: a1_p5.cpp
	g++ -Wall -o problem5 a1_p5.cpp

clean:
	rm problem1 problem2 problem3 problem4 problem5