all: quick modifiedQuicksort

quick: quick.cpp
	g++ -Wall -o quick quick.cpp

modifiedQuicksort: modifiedQuicksort.cpp
	g++ -Wall -o modifiedQuicksort modifiedQuicksort.cpp

clean:
	rm quick modifiedQuicksort