all: sorting sort radixSort

sorting: sorting.cpp
	g++ -Wall -o sorting sorting.cpp

sort: sort.cpp
	g++ -Wall -o sort sort.cpp

radixSort: radixSort.cpp
	g++ -Wall -o radixSort radixSort.cpp

clean:
	rm sorting sort radixSort